//! 网站建站管理（对标宝塔「网站」模块）。
//!
//! 与 `nginx.rs`（反向代理站点）区别：这里管理的是**真实网站**——
//! 带站点根目录（docroot）、可选 PHP-FPM 映射、可选伪静态规则，可创建/删除/启停。
//!
//! 插桩设计：设置环境变量 `VPANEL_DRY_ROOT` 后，所有文件写入与 nginx 校验/reload
//! 都被重定向到 `$VPANEL_DRY_ROOT` 下，命令只会被记录而不真正执行，从而在未安装
//! Nginx 的环境里也能端到端验证控制逻辑（`cargo test` 即用此模式）。

use crate::json;

/// 是否启用 dry-run（插桩模式）。
fn dry() -> bool {
    !std::env::var("VPANEL_DRY_ROOT").unwrap_or_default().is_empty()
}

/// dry-run 模式下把绝对路径重定向到沙盒根下；否则原样返回。
fn dry_prefix(p: &str) -> String {
    match std::env::var("VPANEL_DRY_ROOT") {
        Ok(root) if !root.is_empty() => {
            let trimmed = p.trim_start_matches('/');
            format!("{}/{}", root.trim_end_matches('/'), trimmed)
        }
        _ => p.to_string(),
    }
}

/// nginx 配置根目录（与 nginx.rs 的 VIPanel 约定一致，可被 VPANEL_NGINX_DIR 覆盖）。
fn conf_dir() -> String {
    let base = std::env::var("VPANEL_NGINX_DIR").unwrap_or_else(|_| "/etc/nginx".to_string());
    dry_prefix(&base)
}

fn avail_dir() -> String {
    format!("{}/sites-available", conf_dir())
}
fn enabled_dir() -> String {
    format!("{}/sites-enabled", conf_dir())
}
fn conf_ext() -> &'static str {
    ".conf"
}

/// 网站根目录基础路径（可被 VPANEL_SITE_ROOT 覆盖）。
fn site_base() -> String {
    let base = std::env::var("VPANEL_SITE_ROOT").unwrap_or_else(|_| "/www/wwwroot".to_string());
    dry_prefix(&base)
}

/// 系统 PHP-FPM 默认 unix socket（可被 VPANEL_PHP_SOCKET 覆盖）。
fn php_socket() -> String {
    let s = std::env::var("VPANEL_PHP_SOCKET").unwrap_or_else(|_| "/run/php/php-fpm.sock".to_string());
    dry_prefix(&s)
}

fn available() -> bool {
    std::path::Path::new(&avail_dir()).is_dir()
}

/// 判断启用目录里是否存在指向该配置文件的（符号链接）启用项。
/// 用 symlink_metadata 避免跟随链接导致相对目标判空。
fn link_exists(enabled_dir: &str, fname: &str) -> bool {
    let lnk = std::path::Path::new(enabled_dir).join(fname);
    match std::fs::symlink_metadata(&lnk) {
        Ok(m) => m.file_type().is_symlink() || m.file_type().is_file(),
        Err(_) => false,
    }
}

/// 建立启用软链（用绝对目标，保证链接可解析）。
fn link_enable(name: &str, fname: &str) {
    let _ = std::fs::create_dir_all(enabled_dir());
    let avail = format!("{}/{}", avail_dir(), fname);
    let lnk = format!("{}/{}{}", enabled_dir(), name, conf_ext());
    let _ = std::process::Command::new("ln").args(["-s", &avail, &lnk]).status();
}

fn valid_name(n: &str) -> bool {
    !n.is_empty()
        && n.len() <= 64
        && n.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '.' | '_'))
}

fn valid_domain(d: &str) -> bool {
    let d = d.trim();
    !d.is_empty()
        && d.len() <= 253
        && !d.starts_with('-')
        && d.split('.').all(|label| {
            !label.is_empty()
                && label.len() <= 63
                && label.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
        })
}

/// 真实命令执行（dry-run 时打印到 stderr，模拟成功）。
fn run(cmd: &str) -> (bool, String) {
    if dry() {
        eprintln!("[vpanel:dryrun] {}", cmd);
        return (true, "(dry-run 已跳过)".into());
    }
    let out = std::process::Command::new("/bin/sh").arg("-c").arg(cmd).output();
    match out {
        Ok(o) => {
            let msg = {
                let s = String::from_utf8_lossy(&o.stdout);
                let e = String::from_utf8_lossy(&o.stderr);
                format!("{}{}", s, e).trim().to_string()
            };
            (o.status.success(), msg)
        }
        Err(e) => (false, e.to_string()),
    }
}

/// nginx 配置校验（dry-run 视为通过）。
fn nginx_test() -> (bool, String) {
    run("nginx -t 2>&1")
}

fn nginx_reload() -> (bool, String) {
    run("nginx -s reload 2>&1 || systemctl reload nginx 2>&1")
}

/// 确保目录存在（幂等）。
fn ensure_dir(p: &str) -> std::io::Result<()> {
    std::fs::create_dir_all(p)
}

// ---------------------------------------------------------------------------
// 纯配置生成器（便于单测）
// ---------------------------------------------------------------------------

/// 生成一个纯静态网站的 server 块配置。
pub fn static_site_conf(domain: &str, port: &str, root: &str) -> String {
    format!(
        r#"# auto-generated by vPanel
server {{
    listen {port};
    server_name {domain};
    root {root};
    index index.html index.htm;

    location / {{
        try_files $uri $uri/ =404;
    }}

    access_log /var/log/nginx/{domain}.access.log;
}}
"#,
        port = port,
        domain = domain,
        root = root,
    )
}

/// 生成一个接入 PHP-FPM 的站点配置。
pub fn php_site_conf(domain: &str, port: &str, root: &str, socket: &str) -> String {
    format!(
        r#"# auto-generated by vPanel
server {{
    listen {port};
    server_name {domain};
    root {root};
    index index.php index.html index.htm;

    location / {{
        try_files $uri $uri/ /index.php?$query_string;
    }}

    location ~ \.php$ {{
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass unix:{socket};
    }}

    access_log /var/log/nginx/{domain}.access.log;
}}
"#,
        port = port,
        domain = domain,
        socket = socket,
        root = root,
    )
}

/// 常用伪静态规则生成（对标宝塔内置模板）。
pub fn rewrite_block(kind: &str) -> String {
    match kind {
        "wordpress" | "wp" => r#"location / {
    if (-f $request_filename) { break; }
    if (-e $request_filename) { break; }
    rewrite ^(.+)$ /index.php?q=$1 last;
}
"#
        .into(),
        "thinkphp" => "location / {\n    if (!-e $request_filename) {\n        rewrite ^/(.*)$ /index.php/$1 last;\n    }\n}\n"
            .into(),
        "laravel" => r#"location / {
    try_files $uri $uri/ /index.php?$query_string;
}
"#
        .into(),
        "none" => String::new(),
        _ => String::new(),
    }
}

// ---------------------------------------------------------------------------
// 站点列表
// ---------------------------------------------------------------------------

fn parse_site(content: &str) -> (String, String, String, bool, bool) {
    // 返回 (listen, server_name, root, has_php, enabled)
    let mut listen = String::new();
    let mut server_name = String::new();
    let mut root = String::new();
    let mut has_php = false;
    let mut _enabled = true;
    for line in content.lines() {
        let t = line.trim();
        if let Some(v) = t.find("server_name") {
            if let Some(rest) = t.get(v + "server_name".len()..) {
                if server_name.is_empty() {
                    server_name = rest.split_whitespace().next().unwrap_or("").trim_end_matches(';').to_string();
                }
            }
        } else if t.find("root ").is_some() && !t.starts_with("try_files") {
            if let Some(rest) = t.get(t.find("root").unwrap() + "root".len()..) {
                if root.is_empty() {
                    root = rest.split_whitespace().next().unwrap_or("").trim_end_matches(';').to_string();
                }
            }
        } else if t.starts_with("listen") {
            if let Some(rest) = t.get("listen".len()..) {
                let first = rest.split_whitespace().next().unwrap_or("");
                if listen.is_empty() && !first.contains("ssl") {
                    listen = first.trim_end_matches(';').to_string();
                }
            }
        } else if t.contains("fastcgi_pass") {
            has_php = true;
        }
    }
    (listen, server_name, root, has_php, _enabled)
}

/// 站点列表 -> JSON。
pub fn website_list_json() -> String {
    if !available() {
        return format!("{{\"ok\":false,\"msg\":\"未找到 nginx 配置目录 {}\"}}", json::jesc(&avail_dir()));
    }
    let mut items = Vec::new();
    if let Ok(rd) = std::fs::read_dir(avail_dir()) {
        for ent in rd.flatten() {
            let fname = ent.file_name().to_string_lossy().into_owned();
            if !fname.ends_with(conf_ext()) {
                continue;
            }
            let name = fname.trim_end_matches(conf_ext()).to_string();
            let content = std::fs::read_to_string(ent.path()).unwrap_or_default();
            let (listen, server_name, root, has_php, _) = parse_site(&content);
            let is_website = !root.is_empty(); // 有 root 的才算“网站”（反代站 root 为空）
            if !is_website {
                continue;
            }
            let enabled = link_exists(&enabled_dir(), &fname);
            let docroot = root.clone();
            items.push(format!(
                "{{\"name\":\"{}\",\"domain\":\"{}\",\"listen\":\"{}\",\"root\":\"{}\",\"php\":{},\"enabled\":{}}}",
                json::jesc(&name),
                json::jesc(&server_name),
                json::jesc(&listen),
                json::jesc(&docroot),
                has_php,
                enabled,
            ));
        }
    }
    items.sort();
    format!(
        "{{\"ok\":true,\"basedir\":\"{}\",\"list\":[{}]}}",
        json::jesc(&avail_dir()),
        items.join(",")
    )
}

// ---------------------------------------------------------------------------
// 建站 / 删除 / 启停 / 伪静态
// ---------------------------------------------------------------------------

/// 创建网站。php 为 true 时接入 PHP-FPM。
pub fn website_create(name: &str, domain: &str, port: &str, php: bool) -> (bool, String) {
    if !available() {
        return (false, format!("未找到 nginx 配置目录 {}", avail_dir()));
    }
    if !valid_name(name) {
        return (false, "站点名只能含字母/数字/连字符/点/下划线".into());
    }
    if !valid_domain(domain) {
        return (false, "域名不合法".into());
    }
    let port = port.trim();
    if port.is_empty() || !port.chars().all(|c| c.is_ascii_digit()) {
        return (false, "listen 需为端口数字".into());
    }

    let site_dir = format!("{}/{}", site_base(), name);
    let conf_file = format!("{}/{}{}", avail_dir(), name, conf_ext());
    if std::path::Path::new(&conf_file).exists() {
        return (false, format!("站点 {} 已存在", name));
    }

    // 1) 创建根目录 + 默认首页
    if let Err(e) = ensure_dir(&site_dir) {
        return (false, format!("创建根目录失败：{}", e));
    }
    let idx = format!("{}/index.html", site_dir);
    if !std::path::Path::new(&idx).exists() {
        let default_index = if php {
            "<?php\n// site created by vPanel\nphpinfo();\n".to_string()
        } else {
            format!(
                "<!DOCTYPE html>\n<html><head><meta charset=\"utf-8\"><title>{}</title></head>\n<body><h1>Welcome to {}</h1></body></html>\n",
                domain, domain
            )
        };
        if std::fs::write(&idx, default_index.as_bytes()).is_err() {
            let _ = std::fs::remove_dir_all(&site_dir);
            return (false, format!("写默认首页失败：{}", idx));
        }
    }

    // 2) 生成 nginx 配置
    let conf = if php {
        php_site_conf(domain.trim(), port, &site_dir, &php_socket())
    } else {
        static_site_conf(domain.trim(), port, &site_dir)
    };
    if std::fs::write(&conf_file, conf.as_bytes()).is_err() {
        let _ = std::fs::remove_dir_all(&site_dir);
        return (false, format!("写配置失败：{}", conf_file));
    }

    // 3) 校验 + 启用 + reload
    let (ok, msg) = nginx_test();
    if !ok {
        let _ = std::fs::remove_file(&conf_file);
        let _ = std::fs::remove_dir_all(&site_dir);
        return (false, format!("nginx 配置校验失败（已回滚）：\n{}", msg));
    }
    if !link_exists(&enabled_dir(), &format!("{}{}", name, conf_ext())) {
        link_enable(name, &format!("{}{}", name, conf_ext()));
    }
    let (ro, rm) = nginx_reload();
    let kind = if php { "PHP 站点" } else { "静态站点" };
    if ro {
        (true, format!("{} {} 已创建（根目录 {}）", kind, name, site_dir))
    } else {
        (false, format!("已创建但 reload 失败：{}", rm))
    }
}

/// 启用 / 停用站点。
pub fn website_toggle(name: &str, enable: bool) -> (bool, String) {
    if !valid_name(name) {
        return (false, "非法的站点名".into());
    }
    let avail_file = format!("{}/{}{}", avail_dir(), name, conf_ext());
    if !std::path::Path::new(&avail_file).exists() {
        return (false, format!("站点 {} 不存在", name));
    }
    let lnk = format!("{}/{}{}", enabled_dir(), name, conf_ext());
    if enable {
        if link_exists(&enabled_dir(), &format!("{}{}", name, conf_ext())) {
            return (true, format!("站点 {} 已处于启用状态", name));
        }
        link_enable(name, &format!("{}{}", name, conf_ext()));
    } else {
        let _ = std::fs::remove_file(&lnk);
    }
    let (ok, msg) = nginx_reload();
    if ok {
        (true, format!("站点 {} 已{}", name, if enable { "启用" } else { "停用" }))
    } else {
        (false, format!("reload 失败：{}", msg))
    }
}

/// 删除站点（停用 + 删配置 + 可选删根目录）。
pub fn website_delete(name: &str, drop_root: bool) -> (bool, String) {
    if !valid_name(name) {
        return (false, "非法的站点名".into());
    }
    let avail_file = format!("{}/{}{}", avail_dir(), name, conf_ext());
    if !std::path::Path::new(&avail_file).exists() {
        return (false, format!("站点 {} 不存在", name));
    }
    let lnk = format!("{}/{}{}", enabled_dir(), name, conf_ext());
    let _ = std::fs::remove_file(&lnk);
    let _ = std::fs::remove_file(&avail_file);
    let deleted_root = if drop_root {
        let site_dir = format!("{}/{}", site_base(), name);
        std::fs::remove_dir_all(&site_dir).is_ok()
    } else {
        false
    };
    let (ok, msg) = nginx_reload();
    let mut detail = format!("站点 {} 已删除", name);
    if deleted_root {
        detail.push_str("（根目录已一并删除）");
    }
    if ok {
        (true, detail)
    } else {
        (false, format!("已删除配置，但 reload 失败：{}", msg))
    }
}

/// 给站点应用伪静态规则（在现有配置里插入/替换 location / 块）。
pub fn rewrite_apply(name: &str, kind: &str) -> (bool, String) {
    if !valid_name(name) {
        return (false, "非法的站点名".into());
    }
    let conf_file = format!("{}/{}{}", avail_dir(), name, conf_ext());
    let content = std::fs::read_to_string(&conf_file).unwrap_or_default();
    if content.trim().is_empty() {
        return (false, format!("站点 {} 不存在", name));
    }
    let block = rewrite_block(kind);
    // 简单替换现有的 location / {...} 块
    let rewritten = if block.is_empty() {
        strip_location_root_blocks(&content)
    } else {
        inject_location_root(&content, &block)
    };
    if std::fs::write(&conf_file, rewritten.as_bytes()).is_err() {
        return (false, "写配置失败".into());
    }
    let (ok, msg) = nginx_test();
    if !ok {
        return (false, format!("nginx 配置校验失败：\n{}", msg));
    }
    let (ro, rm) = nginx_reload();
    if ro {
        (true, format!("站点 {} 已应用伪静态规则 {}", name, kind))
    } else {
        (false, format!("配置已写入但 reload 失败：{}", rm))
    }
}

/// 注入 location / 块：把配置中已存在的 `location / {...}` 替换为给定块。
/// 简单实现：按 server_name 后插入，若已含 try_files/rewrite 则总体替换第一个 location / 块。
fn inject_location_root(content: &str, block: &str) -> String {
    // 找到第一个 "location / {" 起始，删除到匹配的 "}"。
    if let Some(start) = content.find("location / {") {
        let before_ok = start > 0 || true;
        let brace_start = start;
        if let Some(end) = find_closing_brace(content, brace_start) {
            let mut out = String::with_capacity(content.len() + block.len());
            if before_ok {
                out.push_str(&content[..start]);
                // 若前面对该 location 有注释扛行 no-op
                out.push_str(block);
                out.push_str("\n");
                out.push_str(&content[end + 1..]);
                return out;
            }
        }
    }
    // 未找到：在第一个 server_name 行之后插入
    if let Some(pos) = content.find("server_name") {
        let line_end = content[pos..].find('\n').map(|i| pos + i).unwrap_or(content.len());
        let mut out = content.to_string();
        out.insert_str(line_end + 1, &format!("\n{}", block));
        return out;
    }
    content.to_string()
}

/// 移除伪静态（恢复默认）：删除注入的 location / 块。
fn strip_location_root_blocks(content: &str) -> String {
    let mut out = String::new();
    let mut rest = content;
    loop {
        match rest.find("location / {") {
            Some(start) => {
                out.push_str(&rest[..start]);
                match find_closing_brace(rest, start) {
                    Some(end) => rest = &rest[end + 1..],
                    None => {
                        out.push_str(rest);
                        break;
                    }
                }
            }
            None => {
                out.push_str(rest);
                break;
            }
        }
    }
    out
}

/// 从字符串的某下标开始，返回与首字符对应的大括号匹配的结束下标（不含闭合符自身）。
fn find_closing_brace(s: &str, open: usize) -> Option<usize> {
    let bytes = s.as_bytes();
    let mut depth = 0i32;
    let mut i = open;
    while i < s.len() {
        match bytes[i] {
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return Some(i);
                }
            }
            _ => {}
        }
        i += 1;
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    /// 构造一个临时沙盒，并把 dry-run 根目录指到它上面。
    /// 由于环境变量全局生效，测试须串行——用同一文件锁保证。
    fn with_sandbox<F: FnOnce()>(td: &std::path::Path, f: F) {
        unsafe {
            std::env::set_var("VPANEL_DRY_ROOT", td.to_str().unwrap());
            std::env::set_var("VPANEL_SITE_ROOT", "/srv/sites");
        }
        // 沙盒里预建 nginx 目录结构
        let _ = std::fs::create_dir_all(td.join("etc/nginx/sites-available"));
        let _ = std::fs::create_dir_all(td.join("etc/nginx/sites-enabled"));
        let _ele = std::fs::create_dir_all(td.join("srv/sites"));
        f();
        unsafe {
            std::env::remove_var("VPANEL_DRY_ROOT");
            std::env::remove_var("VPANEL_SITE_ROOT");
        }
    }

    #[test]
    fn dry_run_create_list_toggle_delete() {
        let td = std::env::temp_dir().join(format!("vpanel_web_test_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&td);

        with_sandbox(&td, || {
            // 建 PHP 站点
            let (ok, msg) = website_create("blog", "blog.example.com", "80", true);
            assert!(ok, "create should succeed: {}", msg);
            let conf = std::fs::read_to_string(td.join("etc/nginx/sites-available/blog.conf")).unwrap();
            assert!(conf.contains("server_name blog.example.com;"), "domain in conf");
            assert!(conf.contains("fastcgi_pass"), "php block present");
            assert!(std::path::Path::new(&td.join("srv/sites/blog/index.html")).exists(), "docroot index created");

            // 列表能识别出它
            let list = website_list_json();
            assert!(list.contains("\"name\":\"blog\""), "list contains blog: {}", list);
            assert!(list.contains("\"php\":true"), "list marks php: {}", list);

            // 应用伪静态
            let (ok, _) = rewrite_apply("blog", "wordpress");
            assert!(ok);
            let after = std::fs::read_to_string(td.join("etc/nginx/sites-available/blog.conf")).unwrap();
            assert!(after.contains("rewrite"), "rewrite injected: {}", after);

            // 移除伪静态
            let (ok, _) = rewrite_apply("blog", "none");
            assert!(ok);
            let cleared = std::fs::read_to_string(td.join("etc/nginx/sites-available/blog.conf")).unwrap();
            assert!(!cleared.contains("rewrite(") && !cleared.contains("rewrite "), "rewrite removed: {}", cleared);

            // 停用 → 删除符号链接；再启用
            let (ok, _) = website_toggle("blog", false);
            assert!(ok);
            assert!(!std::path::Path::new(&td.join("etc/nginx/sites-enabled/blog.conf")).exists());
            let (ok, _) = website_toggle("blog", true);
            assert!(ok);

            // 静态站点
            let (ok, _) = website_create("static1", "a.example.com", "8080", false);
            assert!(ok);
            let sconf = std::fs::read_to_string(td.join("etc/nginx/sites-available/static1.conf")).unwrap();
            assert!(!sconf.contains("fastcgi_pass"), "static site has no php");
            assert!(sconf.contains("try_files"), "static site try_files");

            // 删除（删除根目录）
            let (ok, msg) = website_delete("blog", true);
            assert!(ok, "delete should succeed: {}", msg);
            assert!(!std::path::Path::new(&td.join("etc/nginx/sites-available/blog.conf")).exists());
            assert!(!std::path::Path::new(&td.join("srv/sites/blog")).exists(), "docroot removed");
        });

        let _ = std::fs::remove_dir_all(&td);
    }

    #[test]
    fn config_generators_validate_ports() {
        let s = static_site_conf("x.com", "80", "/tmp/root");
        assert!(s.contains("listen 80;"));
        assert!(s.contains("root /tmp/root;"));
        let p = php_site_conf("x.com", "80", "/tmp/root", "/run/php/php-fpm.sock");
        assert!(p.contains("fastcgi_pass unix:/run/php/php-fpm.sock;"));
        // 非法输入
        assert!(!valid_domain("-bad.com"));
        assert!(!valid_name("../evil"));
        assert!(valid_name("good-site_1"));
    }
}